\c alpha

--*
--* zappos
--*
INSERT INTO product_apis (id, provider, status) VALUES (DEFAULT, 'zappos', 0);

INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 1, '482440', 'Gia Slide', 45.99, 3, 'Kenneth Cole New York', 'https://www.6pm.com/p/kenneth-cole-new-york-gia-slide-medium-brown-smooth/product/9216516/color/97952', NULL, 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 1, '357172', 'Plus Size Cotton Modal Pointelle Knit Cap Sleeve Waltz Nightgown', 61.2, 0, 'Eileen West', 'https://www.zappos.com/p/eileen-west-plus-size-cotton-modal-pointelle-knit-cap-sleeve-waltz-nightgown-white-ground-blue-mono-floral/product/9383195/color/864329', NULL, 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 1, '482453', 'Wiley Strap Sandal', 115.5, 2, 'Grenson', 'https://www.6pm.com/p/grenson-wiley-strap-sandal-black-calf/product/9227317/color/60', NULL, 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 1, '483953', 'Sleeveless Buttoned Front Animal Print Midi Crepe Dress', 41.3, 3, 'Donna Morgan', 'https://www.6pm.com/p/donna-morgan-sleeveless-buttoned-front-animal-print-midi-crepe-dress-brown-multi/product/9291596/color/3091', NULL, 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 1, '506839', 'Sara2', 77.99, 0, 'Via Spiga', 'https://www.6pm.com/p/via-spiga-sara2-black/product/9295603/color/3', NULL, 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 1, '484153', 'Nova Mid-Volume Light', 42.99, 4, 'Herschel Supply Co.', 'https://www.6pm.com/p/herschel-supply-co-nova-mid-volume-light-khaki-green/product/9151463/color/25690', NULL, 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 1, '574527', 'Hamond', 24, 4, 'Dolce Vita', 'https://www.6pm.com/p/dolce-vita-hamond-blush-suede/product/8979361/color/10909', NULL, 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 1, '484179', 'Soft Midi Briefs', 20.64, 0, 'HOM', 'https://www.6pm.com/p/hom-soft-midi-briefs-white/product/9257776/color/14', NULL, 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 1, '571607', 'Emma (Little Kid/Big Kid)', 22.99, 0, 'bernie mev. Kids', 'https://www.6pm.com/p/bernie-mev-kids-emma-little-kid-big-kid-black-blush-chenille/product/9309956/color/838196', NULL, 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 1, '571608', 'Emma (Little Kid/Big Kid)', 25.99, 0, 'bernie mev. Kids', 'https://www.6pm.com/p/bernie-mev-kids-emma-little-kid-big-kid-black-black-pewter-chenille/product/9309956/color/838195', NULL, 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 1, '571653', 'Paityn', 129.95, 5, 'Alegria', 'https://www.6pm.com/p/alegria-paityn-sprinkles/product/9473014/color/362522', NULL, 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 1, '484143', 'Teton', 46, 4, 'Born', 'https://www.6pm.com/p/born-teton-light-blue-full-grain-leather/product/9168729/color/733686', NULL, 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 1, '484187', 'One 5.4 FG/AG Jr Soccer (Little Kid/Big Kid)', 17.99, 5, 'Puma Kids', 'https://www.6pm.com/p/puma-kids-one-5-4-fg-ag-jr-soccer-little-kid-big-kid-puma-black-nrgy-red-puma-aged-silver/product/9257874/color/816841', NULL, 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 1, '448430', 'Ultra Stretch Longer Length Cami', 15.26, 3, 'Coobie', 'https://www.zappos.com/p/coobie-ultra-stretch-longer-length-cami-medium-gray/product/9149285/color/57046', NULL, 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 1, '495607', 'You - 15818', 42.99, 4, 'SKECHERS Performance', 'https://www.6pm.com/p/skechers-performance-you-15818-black-multi/product/9269999/color/1415', NULL, 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 1, '495629', 'Ludlow High', 57.99, 5, 'Frye', 'https://www.6pm.com/p/frye-ludlow-high-loden-wool/product/8980253/color/769890', NULL, 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 1, '581613', 'Winter Rebellion&#8482; Down Parka', 157.99, 2, 'Columbia', 'https://www.6pm.com/p/columbia-winter-rebellionn-down-parka-black/product/9230491/color/3', NULL, 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 1, '495878', 'Gel-Ziruss 3', 104.99, 0, 'ASICS', 'https://www.6pm.com/p/asics-gel-ziruss-3-peacoat-safety-yellow/product/9224920/color/543874', NULL, 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 1, '491521', 'Logo Solids Belted Bottoms', 48.6, 0, 'MICHAEL Michael Kors', 'https://www.6pm.com/p/michael-michael-kors-logo-solids-belted-bottoms-black/product/9371347/color/3', NULL, 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 1, '582572', 'Spire 3', 77.99, 5, '361 Degrees', 'https://www.6pm.com/p/361-degrees-spire-3-flame-black/product/9089682/color/106131', NULL, 0);

INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 1, 'https://www.6pm.com/images/z/4/6/8/5/2/9/4685295-t-THUMBNAIL.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 2, 'https://www.zappos.com/images/z/5/0/5/0/1/3/5050136-t-THUMBNAIL.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 3, 'https://www.6pm.com/images/z/4/7/1/0/6/3/4710636-t-THUMBNAIL.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 4, 'https://www.6pm.com/images/z/4/8/4/9/6/6/4849669-t-THUMBNAIL.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 5, 'https://www.6pm.com/images/z/4/8/5/7/7/8/4857784-t-THUMBNAIL.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 6, 'https://www.6pm.com/images/z/4/9/1/3/9/2/4913929-t-THUMBNAIL.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 7, 'https://www.6pm.com/images/z/4/1/7/6/7/1/4176714-t-THUMBNAIL.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 8, 'https://www.6pm.com/images/z/4/7/8/1/3/3/4781334-t-THUMBNAIL.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 9, 'https://www.6pm.com/images/z/4/8/8/3/8/5/4883854-t-THUMBNAIL.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 10, 'https://www.6pm.com/images/z/4/8/8/3/8/5/4883855-t-THUMBNAIL.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 11, 'https://www.6pm.com/images/z/4/7/8/5/7/5/4785757-t-THUMBNAIL.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 12, 'https://www.6pm.com/images/z/4/5/9/0/6/7/4590675-t-THUMBNAIL.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 13, 'https://www.6pm.com/images/z/4/7/8/1/5/4/4781546-t-THUMBNAIL.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 14, 'https://www.zappos.com/images/z/4/5/4/2/5/0/4542507-t-THUMBNAIL.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 15, 'https://www.6pm.com/images/z/4/8/0/6/9/2/4806928-t-THUMBNAIL.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 16, 'https://www.6pm.com/images/z/4/4/3/8/8/7/4438874-t-THUMBNAIL.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 17, 'https://www.6pm.com/images/z/4/7/1/9/6/7/4719676-t-THUMBNAIL.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 18, 'https://www.6pm.com/images/z/4/9/0/6/4/7/4906470-t-THUMBNAIL.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 19, 'https://www.6pm.com/images/z/5/0/2/5/4/7/5025473-t-THUMBNAIL.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 20, 'https://www.6pm.com/images/z/4/4/2/2/3/1/4422319-t-THUMBNAIL.jpg');

--*
--* makeup
--*
INSERT INTO product_apis (id, provider, status) VALUES (DEFAULT, 'makeup', 0);

INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 2, '1048', 'Lippie Pencil', 5.0, NULL, 'colourpop', 'https://colourpop.com/collections/lippie-pencil', 'Lippie Pencil A long-wearing and high-intensity lip pencil that glides on easily and prevents feathering. Many of our Lippie Stix have a coordinating Lippie Pencil designed to compliment it perfectly, but feel free to mix and match!', 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 2, '1047', 'Blotted Lip', 5.5, NULL, 'colourpop', 'https://colourpop.com/collections/lippie-stix?filter=blotted-lip', 'Blotted Lip Sheer matte lipstick that creates the perfect popsicle pout! Formula is lightweight, matte and buildable for light to medium coverage.', 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 2, '1046', 'Lippie Stix', 5.5, NULL, 'colourpop', 'https://colourpop.com/collections/lippie-stix', 'Lippie Stix Formula contains Vitamin E, Mango, Avocado, and Shea butter for added comfort and moisture. None of our Lippie formulas contain any nasty ingredients like Parabens or Sulfates.', 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 2, '1045', 'No Filter Foundation', 12.0, NULL, 'colourpop', 'https://colourpop.com/products/no-filter-matte-foundation', 'Developed for the Selfie Age, our buildable full coverage, natural matte foundation delivers flawless looking skin from day-to-night. The oil-free, lightweight formula blends smoothly and is easily customizable to create the coverage you want. Build it up or sheer it out, it was developed with innovative soft-blurring pigments to deliver true color while looking and feeling natural. The lockable pump is easy to use and keeps your routine mess-free! As always, 100% cruelty-free and vegan.', 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 2, '1044', 'Lipstick', 26.0, NULL, 'boosh', 'https://www.boosh.ca/collections/all', 'All of our products are free from lead and heavy metals, parabens, phthalates, artificial colourants, and synthetic fragrances.  Boosh lipstick glides on smoothly for clean & protective SPF coverage. They are filled with hydrating oils and butters to preserve and enhance your lips natural surface. Organic sweet orange oil gives a light and cheerful scent.', 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 2, '1043', 'Serum Foundation', 6.7, NULL, 'deciem', 'https://deciem.com/product/rdn-serum-foundation-30-r-30ml', 'Serum Foundations are lightweight medium-coverage formulations available in a comprehensive shade range across 21 shades. These foundations offer moderate coverage that looks natural with a very lightweight serum feel. They are very low in viscosity and are dispensed with the supplied pump or with the optional glass dropper available for purchase separately if preferred. ', 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 2, '1042', 'Coverage Foundation', 6.9, NULL, 'deciem', 'https://deciem.com/product/rdn-coverage-foundation-33-n-30ml', 'Coverage Foundations are full-coverage formulations available in a comprehensive shade range across 21 shades. These foundations contain higher pigment levels than our Serum Foundations but still offer a smooth finish that avoids the heavy makeup look that can make skin appear more aged. The texture is that of a lightweight, non-oily cream.', 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 2, '1041', 'Liquid Liner', 0.0, NULL, 'zorah biocosmetiques', 'https://www.purpicks.com/product/zorah-biocosmetiques-liquid-liner/', '<strong>12 hours of long-lasting</strong> intense color, transfer-free (leaves no trace on crease above the eyelid) <strong>Pure Light Capture®</strong> <strong>minerals</strong> deliver color and radiance. Silky lines and refreshingly light, Pure Argan eyeliner leaves a weightless feel on the eyelids.<p align=''LEFT''>Natural cosmetic certified by Ecocert Greenlife according to Ecocert Standard available at: http://cosmetiques.ecocert.com</p>98% of the total ingredients are from natural origin 5% of total ingredients are from organic farming', 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 2, '1040', 'Eyeshadow', 0.0, NULL, 'zorah biocosmetiques', 'https://www.purpicks.com/product/zorah-eyeshadow/', '<strong>Product Description</strong>Anti-aging formula made with organic Pure Argan oil and Pure Light Capture<sup>®</sup> pigments. 24 Hour crease-free intensity (no build-up increase of eyelid), no running. Pure Light Capture® pigments deliver color and luminosity. Silky and refreshingly light feel, Pure Argan eyeshadow is weightless on the eyelids. Pure Argan eyeshadow <strong>soothes</strong>, <strong>hides redness </strong>and <strong>slows the appearance of the signs of aging on the skin.</strong><p align=''LEFT''>Natural cosmetic certified by Ecocert Greenlife according to Ecocert Standard available at: http://cosmetiques.ecocert.com</p>100% of the total ingredients are from natural origin5% of total ingredients are from organic farming', 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 2, '1039', ' Realist Invisible Setting Powder', 0.0, NULL, 'w3llpeople', 'https://www.purpicks.com/product/w3llpeople-realist-invisible-setting-powder/', '<span style="font-weight: 400;">Keep it real with a polished, soft-focus look using this superfine, loose mineral powder. The healing properties of organic aloe help soothe and calm stressed out skin. Instantly minimize pores, soften imperfections, and creates a matte finish with superfine powder. Use by itself for an air-brushed look, or to set foundation for ultra-long wear.</span><span style="font-weight: 400;">* Set makeup or by itself for matte air-brushed effect</span><span style="font-weight: 400;">* Absorbs excess oil while softening fine lines</span><span style="font-weight: 400;">* Organic aloe creates radiant, rejuvenated skin</span><span style="font-weight: 400;">* Hypoallergenic, Chemical Free, Cruelty Free &amp; Noncomedogenic </span><span style="font-weight: 400;">* EWG Verified for non-toxic health and safety</span><span style="font-weight: 400;">* Free From: Parabens, Gluten, GMO, Phthalates, Sulfates, Fragrance, Pheonoxyethanol, Dimethicone, PEG, Propylene Glycol, Butylene Glycol, Lead, Mineral Oil, Talc</span>', 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 2, '1038', 'B Smudged', 0.0, NULL, 'sally b''s skin yummies', 'https://www.purpicks.com/product/sally-bs-skin-yummies-b-smudged/', 'Let your eyes naturally pop with our B Smudged, a subtle eye color that adds a tint of color to the base of your lashes. An organic, cream eye color, B Smudged eliminates the inevitable uneven line from traditional eyeliners, and does not require expert blending techniques of messy, powder-based shadows. Simply ''smudge'' along lash line for color that stays in place for a long lasting look.', 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 2, '1037', 'B Glossy Lip Gloss', 0.0, NULL, 'sally b''s skin yummies', 'https://www.purpicks.com/product/sally-bs-skin-yummies-b-glossy-lip-gloss/', 'Intensify your natural lip color with Sally B''s B Glossy Lip Gloss, an organic lip gloss that adds a silky smooth hint of color and shimmer to lips. Formulated with 98% certified organic, moisture-rich ingredients our B Glossy Lip Gloss works to enrich lip health for lips that feel good and look even better.', 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 2, '1036', 'Multi Purpose Powder - Blush & Eye', 0.0, NULL, 'rejuva minerals', 'https://www.purpicks.com/product/rejuva-minerals-multi-purpose-powder-blush-eye/', 'Our Multi Purpose Pressed Powders may be used for blush or eye shadow. Blended with antioxidants from Certified Organic Fruits, Berries &amp; Botanicals*. Made without any gluten containing ingredients. Mica free Pink Parfait and Papaya will offer a natural, ultra sheer semi-matte finish. The petals from beautiful crushed red roses that are found in Pink Parfait, are valued for their natural color and delightful aroma that they provide! Acai Berry will offer a natural, ultra sheer satin finish (mica added). VEGAN. Image one is Pink Parfait. Image two is Papaya, and image three is Acai Berry. Model in image four is wearing Papaya. Model in image five is wearing Acai Berry. To see a demonstration of Papaya, click on the video and fast forward to 3:44. Enjoy! This product is EWG VERIFIED&#x2122; and rated ''CLEAN''in the Think Dirty app! BPA and Phthalate free packaging. Plastic parts of compacts are recyclable. *Tiny flecks of fruit and botanical particles may be visible in powder. Pink Parfait and Papaya are Titanium Dioxide and Mica free. Net Weight: 2.8 gm.', 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 2, '1035', 'Multi Purpose Powder - Blush & Eye', 0.0, NULL, 'rejuva minerals', 'https://www.purpicks.com/product/rejuva-minerals-multi-purpose-powder-blush-eye/', 'Our Multi Purpose Pressed Powders may be used for blush or eye shadow. Blended with antioxidants from Certified Organic Fruits, Berries &amp; Botanicals*. Made without any gluten containing ingredients. Mica free Pink Parfait and Papaya will offer a natural, ultra sheer semi-matte finish. The petals from beautiful crushed red roses that are found in Pink Parfait, are valued for their natural color and delightful aroma that they provide! Acai Berry will offer a natural, ultra sheer satin finish (mica added). VEGAN. Image one is Pink Parfait. Image two is Papaya, and image three is Acai Berry. Model in image four is wearing Papaya. Model in image five is wearing Acai Berry. To see a demonstration of Papaya, click on the video and fast forward to 3:44. Enjoy! This product is EWG VERIFIED&#x2122; and rated ''CLEAN''in the Think Dirty app! BPA and Phthalate free packaging. Plastic parts of compacts are recyclable. *Tiny flecks of fruit and botanical particles may be visible in powder. Pink Parfait and Papaya are Titanium Dioxide and Mica free. Net Weight: 2.8 gm.', 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 2, '1034', 'Multi Purpose Powder - Eye Shadow & Face', 0.0, NULL, 'rejuva minerals', 'https://www.purpicks.com/product/rejuva-minerals-multi-purpose-powder-eye-shadow-face/', 'Our Multi Purpose Pressed Powders may be used as eye shadow, brow powder, eye liner, or for highlighting. Blended with antioxidants from Certified Organic Fruits, Berries &amp; Botanicals*. No gluten derived ingredients. VEGAN. All shades will offer a semi-matte finish, with the exception of White Diamond. White Diamond will offer a shimmery finish. Image one shows shade in Iris. This product is EWG VERIFIED&#x2122; and rated ''CLEAN'' in the Think Dirty app! BPA and Phthalate free packaging. Plastic parts of compacts are recyclable.', 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 2, '1033', 'Pressed Powder Foundation', 0.0, NULL, 'rejuva minerals', 'https://www.purpicks.com/product/rejuva-minerals-multi-purpose-powder-eye-shadow-face/', 'Coconut Cream - Warm Undertones (yellow) Light Shade. May also be used as a highlighting shade! About our pressed foundations:<ul><li>Provides a silky smooth, natural ''semi-matte'' finish</li><li>All skin types</li><li>Will not dry out skin (apply light moisturizer underneath for best results)</li><li>Resists caking and settling in lines and pores</li><li>Layers to provide a light-medium (buildable) coverage</li><li>Eco-friendly, biodegradable compact</li><li>Colored with minerals and enhanced with organic fruits and botanicals</li><li>Infused with conditioning organic jojoba oil</li><li>Formulated without common skin irritants.</li></ul>', 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 2, '1032', 'Bronzer - loose', 0.0, NULL, 'rejuva minerals', 'https://www.purpicks.com/product/rejuva-minerals-bronzer-caribbean/', 'Caribbean is a multi-purpose shade that is suitable for medium-tan skin tones. This shade may be used as a bronzer, or as a contour shade. <ul><li>Our bronzer has been enhanced with Fruits, Botanicals and Clays for their natural color, fragrance and antioxidant benefits!</li><li>Blended with Certified Organics Fruits and Botanicals</li><li>Formulated with common skin irritants.</li><li>Our bronzer will offer a natural “ultra sheer” semi-matte finish.</li><li>Made without any gluten containing ingredients</li><li>VEGAN!</li><li>Eco Friendly jars!</li></ul>', 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 2, '1031', 'Bronzer - pressed', 0.0, NULL, 'rejuva minerals', 'https://www.purpicks.com/product/rejuva-bronzer-light/', 'Our bronzer has been enhanced with Fruits, Botanicals and Clays for their natural color, fragrance and antioxidant benefits! Blended with Certified Organics Fruits and Botanicals Formulated with common skin irritants. Our bronzer will offer a natural ''ultra sheer'' semi-matte finish. Made without any gluten containing ingredients VEGAN! Eco Friendly jars!', 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 2, '1030', 'Lip Gloss', 0.0, NULL, 'penny lane organics', 'https://www.purpicks.com/product/penny-lane-organics-lip-gloss/', 'For fuller healthier lips! Long lasting colour! This colour is a good choice for any skin tone. It can be made lighter by wiping some off after application.Please note that our Vitamin E is extracted from non-GMO soy bean oil and therefore is gluten-free.', 0);
INSERT INTO products (id, api_id, product_id, name, price, rating, brand, link, description, status) VALUES (DEFAULT, 2, '1029', 'Amalia', 0.0, NULL, 'nudus', 'https://www.purpicks.com/product/nudus-amalia/', 'named after my beautiful mum, delicately pink that displays sophistication. a perfect sheer wash of gorgeous colour that brings a new texture to the lip euphoria range. <strong>lipstick benefits</strong> a unique handcrafted lipstick blended with certified organic ingredients. beautifully pigmented with ancient ayurvedic bioactive colour extracts, leaving your lips soft and deliciously hydrated.<strong>key benefits</strong><ul><li>vitamins, A, B, C, D, E and K</li><li>antioxidants, including pomegranate, raspberry and kiwi cold pressed oils</li><li>27 active natural ingredients, helping against environmental stress</li><li>colours made from flowers, fruits, herbs and minerals</li><li>free from parabens, petro-chemicals, lanolin, hydrogenated oils,fd&amp;c and lake dyes, nano-particles, gmo, pesticides and fungicides</li><li>not tested on animals</li><li>gluten free</li></ul>', 0);

INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 21, 'https://cdn.shopify.com/s/files/1/1338/0845/collections/lippie-pencil_grande.jpg?v=1512588769');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 22, 'https://cdn.shopify.com/s/files/1/1338/0845/products/brain-freeze_a_800x1200.jpg?v=1502255076');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 23, 'https://cdn.shopify.com/s/files/1/1338/0845/collections/blottedlip-lippie-stix_grande.jpg?v=1512588803');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 24, 'https://cdn.shopify.com/s/files/1/1338/0845/products/foundations-lineup_800x1200.jpg?v=1528927785');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 25, 'https://cdn.shopify.com/s/files/1/1016/3243/products/LIPBALM_LID_grande.jpg?v=1496848378');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 26, 'https://3bc01d2807fb1bc0d25c-a86d2521f1af8989841b9619f5314be5.ssl.cf1.rackcdn.com/products/market-img/rdn-serum-foundation-30-r-30ml.png?v=6ab9fcb8ca2abb9828afcf9dcdad9f94');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 27, 'https://3bc01d2807fb1bc0d25c-a86d2521f1af8989841b9619f5314be5.ssl.cf1.rackcdn.com/products/market-img/rdn-coverage-foundation-33-n-30ml.png?v=daa322f179d80e450613c75826602292');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 28, 'https://www.purpicks.com/wp-content/uploads/2018/06/Zorah-Biocosmetiques-Liquid-Liner.png');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 29, 'https://www.purpicks.com/wp-content/uploads/2018/02/Ombre-Amazonie-CC.png');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 30, 'https://www.purpicks.com/wp-content/uploads/2018/06/w3llpeople-Realist-Invisible-Setting-Powder.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 31, 'https://www.purpicks.com/wp-content/uploads/2018/06/Sally-B_s-Skin-Yummies-B-Smudged-1.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 32, 'https://www.purpicks.com/wp-content/uploads/2018/06/Sally-B_s-Skin-Yummies-B-Glossy-Lip-Gloss.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 33, 'https://www.purpicks.com/wp-content/uploads/2018/06/Rejuva-Minerals-Multi-Purpose-Powder-Blush-_-Eye-1.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 34, 'https://www.purpicks.com/wp-content/uploads/2018/06/Rejuva-Minerals-Multi-Purpose-Powder-Blush-_-Eye-1.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 35, 'https://www.purpicks.com/wp-content/uploads/2018/06/Rejuva-Minerals-Multi-Purpose-Powder-Eye-Shadow-Face-1.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 36, 'https://www.purpicks.com/wp-content/uploads/2018/06/Rejuva-Minerals-Multi-Purpose-Powder-Eye-Shadow-Face-1.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 37, 'https://www.purpicks.com/wp-content/uploads/2018/03/rejuva-minerals-bronzer.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 38, 'https://www.purpicks.com/wp-content/uploads/2018/03/rejuva-minerals-bronzer.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 39, 'https://www.purpicks.com/wp-content/uploads/csm/sunset-bronze-pennylaneorganics1.jpg');
INSERT INTO product_images (id, product_id, image_link) VALUES (DEFAULT, 40, 'https://www.purpicks.com/wp-content/uploads/2018/06/Nudus-Amalia.jpg');

